import { OmitType } from '@nestjs/swagger'
import { EventDto } from './event.dto'

// omit the id property because it will be generated by the database
export class CreateEventDto extends OmitType(EventDto, ['id']) {}
